name: Build (Ubuntu)

on:
  push:
    branches:
      - ai-fsm-utility
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches:
      - ai-fsm-utility

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type: ["Release"]
        cmake_generator: ["Ninja"]

        config:
        - {
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            os: ubuntu-latest,
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'ai-fsm-utility'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y ninja-build

    - name: Build SDL2 from sources
      run: |
        mkdir -p ${{ steps.strings.outputs.build-output-dir }}/sdl-dev-libs
        cd ${{ steps.strings.outputs.build-output-dir }}/sdl-dev-libs
        wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.1/SDL2-2.30.1.tar.gz
        wget https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-2.8.2.tar.gz
        wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.8.0/SDL2_mixer-2.8.0.tar.gz
        tar -xf SDL2-2.30.1.tar.gz
        tar -xf SDL2_image-2.8.2.tar.gz
        tar -xf SDL2_mixer-2.8.0.tar.gz
        cd SDL2-2.30.1
        cmake -S . -B build \
          -DSDL2MIXER_OPUS=OFF \
          -DSDL2MIXER_MIDI=OFF \
          -DSDL2MIXER_MP3=OFF \
          -DSDL2MIXER_MOD=OFF \
          -DSDL2MIXER_GME=OFF \
          -DSDL2MIXER_FLAC=OFF \
          -DSDL2MIXER_CMD=OFF \
          -DSDL2MIXER_VENDORED=OFF
        cmake --build build
        sudo cmake --install build
        cd ../SDL2_image-2.8.2
        cmake -S . -B build \
          -DSDL2MIXER_OPUS=OFF \
          -DSDL2MIXER_MIDI=OFF \
          -DSDL2MIXER_MP3=OFF \
          -DSDL2MIXER_MOD=OFF \
          -DSDL2MIXER_GME=OFF \
          -DSDL2MIXER_FLAC=OFF \
          -DSDL2MIXER_CMD=OFF \
          -DSDL2MIXER_VENDORED=OFF
        cmake --build build
        sudo cmake --install build
        cd ../SDL2_mixer-2.8.0
        cmake -S . -B build \
          -DSDL2MIXER_OPUS=OFF \
          -DSDL2MIXER_MIDI=OFF \
          -DSDL2MIXER_MP3=OFF \
          -DSDL2MIXER_MOD=OFF \
          -DSDL2MIXER_GME=OFF \
          -DSDL2MIXER_FLAC=OFF \
          -DSDL2MIXER_CMD=OFF \
          -DSDL2MIXER_VENDORED=OFF
        cmake --build build
        sudo cmake --install build

    - name: Configure CMake
      run: >
        cmake
        -G ${{ matrix.cmake_generator }}
        -S ${{ github.workspace }}
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
        -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: >
        cmake
        --build ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}

